#!/bin/bash
export NODE_PATH=${NODE_PATH:-"/usr/lib/node_modules/"}
ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#5ED3F3"}

# Create your command here
node -e "const react=require('react'); console.log(react.version)" | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $1}'

echo $SHORT_VERSION
echo $COLOR