#!/bin/bash

ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#199F4B"}

# Create your command here
vim --version | awk 'NR==1 {print $5}' | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $1}'

echo $SHORT_VERSION
echo $COLOR