#!/bin/bash

ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#009137"}

# Create your command here
ngx --version | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $1}'
echo $SHORT_VERSION
echo $COLOR