#!/bin/bash

ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#4F5D95"}

# Create your command here
php --version | cut -c5-10 | awk -v icon=$ICON -v prefix=$PREFIX 'NR==1 {print icon " " prefix $1}'
echo $SHORT_VERSION
echo $COLOR