#!/bin/bash
export JAVA_HOME=${JAVA_HOME:-"/usr/"}
ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#E69F56"}

groovy --version 2>/dev/null | awk '{ print $3}' | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $1}'

echo $SHORT_VERSION
echo $COLOR