#!/bin/bash

ICON=${ICON:-"PIP"}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#544327"}

pip --version | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $2}'

echo $SHORT_VERSION
echo $COLOR