#!/bin/bash


ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#F7CA3E"}

python --version | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $2}'

echo $SHORT_VERSION
echo $COLOR
