#!/bin/bash

ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#D94C37"}

ember --version 2>/dev/null | grep ember-cli | awk '{print $2}' | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $1}'

echo $SHORT_VERSION
echo $COLOR