#!/bin/bash

ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#FEB672"}

# Enter command here
grails --version 2>/dev/null | awk 'NR==1 {print $4}' | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $1}'

echo $SHORT_VERSION
echo $COLOR
