#!/bin/bash

ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#264977"}

# Enter command here
less --version | cut -c6-9 | awk 'NR==1' | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $1}'

echo $SHORT_VERSION
echo $COLOR
