#!/bin/bash

ICON=${ICON:-""}
PREFIX=${PREFIX:-"v"}
SHORT_VERSION=${SHORT_VERSION:-""}
COLOR=${COLOR:-"#27314A"}

# Enter command here
coffee --version | awk '{print $3}' | awk -v icon=$ICON -v prefix=$PREFIX '{print icon " " prefix $1}'

echo $SHORT_VERSION
echo $COLOR
